### ISSUE TITLE
docker image and chart dependencies

### ISSUE THREAD

**Issue by gimler** [helm/chart-releaser#114]
Remote dependencies does not work with docker image

Chart.yaml
```
dependencies:
- name: redis-ha
  version: "4.12.9"
  repository: "https://dandydeveloper.github.io/charts"
```

command running from docker image
```
cr package charts/sap-event-ticketing/
```

error
```
Error: no repository definition for https://dandydeveloper.github.io/charts
```

workaround add helm and repo than it works
```
apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing helm
helm repo add dandydev https://dandydeveloper.github.io/charts
```

Solution 1:
Install helm into the docker image

Solution 2:
let chart-releaser fetch the repo data to
```
~/.cache/helm/repository/dandydev-charts.txt
~/.cache/helm/repository/dandydev-index.yaml
```

For solution 1 i can open a PR.
