### ISSUE TITLE
Missing tgz package file on gh-pages branch.

### ISSUE THREAD

**Issue by yunwz** [helm/chart-releaser#524]
I'm using `chart-releaser-actoin`(v1.7.0) to publishing tgz package file and `index.yaml` file.
This is the github action config in my github repository (https://github.com/YunWZ/nacos-k8s/blob/92a42759ca005c8e502787914ddc46600eda395a/.github/workflows/release.yml):
```yaml
...
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
        with:
          skip_existing: false
          charts_dir: 'charts'
          packages_with_index: true
          pages_branch: gh-pages
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_GENERATE_RELEASE_NOTES: true
...
```

And the flowing context is the latest runed job output: 
```text
Run helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f
  with:
    skip_existing: false
    charts_dir: charts
    packages_with_index: true
    pages_branch: gh-pages
    version: v1.7.0
    mark_as_latest: true
  env:
    CR_TOKEN: ***
    CR_GENERATE_RELEASE_NOTES: true
Run owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
Looking up latest tag...
Discovering changed charts since 'nacos-1.0.0'...
Installing chart-releaser on /opt/hostedtoolcache/cr/v1.7.0/x86_64...
Adding cr directory to PATH...
Packaging chart 'charts/nacos'...
Successfully packaged chart in /home/runner/work/nacos-k8s/nacos-k8s/charts/nacos and saved it to: .cr-release-packages/nacos-1.0.0.tgz
Releasing charts...
Preparing worktree (detached HEAD 8[2](https://github.com/yunwz/nacos-k8s/actions/runs/15418324155/job/43387189238#step:6:2)42ad9)
HEAD is now at 8242ad9 remove *.tgz from gh-pages
Pushing to branch "gh-pages"
Everything up-to-date
Updating charts repo index...
Loading index file from git repository index.yaml
Preparing worktree (detached HEAD 82[4](https://github.com/yunwz/nacos-k8s/actions/runs/15418324155/job/43387189238#step:6:4)2ad9)
HEAD is now at 8242ad9 remove *.tgz from gh-pages
Found nacos-1.0.0.tgz
Extracting chart metadata from .cr-release-packages/nacos-1.0.0.tgz
Calculating Hash for .cr-release-packages/nacos-1.0.0.tgz
Updating index index.yaml
From https://github.com/yunwz/nacos-k8s
 * branch            gh-pages   -> FETCH_HEAD
Already up to date.
[detached HEAD b1edc14] Update index.yaml
 1 file changed, 19 insertions(+)
 create mode 100[6](https://github.com/yunwz/nacos-k8s/actions/runs/15418324155/job/43387189238#step:6:6)44 index.yaml
Pushing to branch "gh-pages"
To https://github.com/yunwz/nacos-k[8](https://github.com/yunwz/nacos-k8s/actions/runs/15418324155/job/43387189238#step:6:8)s
   8242ad9..b1edc14  HEAD -> gh-pages
``` 

I had noticed the `index.yaml` file has been uploaded to `gh-pages` branch, but `acos-1.0.0.tgz` did't upload to `gh-pages` branch. Why?
